### ISSUE TITLE
Setup problem w/ Xen 4.11 and Windows 7

### ISSUE THREAD

**Issue by Necroxys77** [Wenzel/r2vmi#38]
Hi,

I'm trying to get r2vmi up and running but I'm having some problems.
Before giving a look to r2vmi I configured my environment following the installation guide of [DRAKVUF](https://drakvuf.com/). So I have:

- Xen 4.11
- Windows 7 32-bit (domU)
- Ubuntu 18.04 (dom0)
- DRAKVUF, that runs correctly

Following your Project Setup guide I noticed that some steps are more or less equal to some that I followed for installing DRAKVUF. The steps that I didn't followed were related to Libvirt configuration, in "Windows 7 VM" section.
Doing the last check I get the correct output:
`necroxys:~$ r2 -L | grep vmi`
`rwd  vmi      VMI IO plugin for r2 vmi://[vm_name]:[pid] (LGPL)`

However, after booting my domU with xl create, I can't inspect any process:
`root:/home/necroxys# r2 -d vmi://windows7-sp1:explorer`
`[r] Cannot open 'vmi://windows7-sp1:explorer' `
where:
`root:/home/necroxys# xl list`
`Name                                        ID   Mem VCPUs	State	Time(s)`
`Domain-0                                     0  4095     4     r-----     895.1`
`windows7-sp1                                 1  3000     2     r-----       3.5`

I don't know if I misunderstood the usage of radare2 and - consequently - r2vmi.
Am I missing something important?

Thank you.

**Comment by Wenzel** [comment]
Hi,

I'm surprised you don't get much output.
The function which is opening and setting up the plugin is here and it should have enough debug output:
https://github.com/Wenzel/r2vmi/blob/master/io_vmi.c#L50

To my understanding, this looks like more an issue between `radare2` and the plugin itself.
Can you rerun with `R_DEBUG` variable to get more output from `radare2` ?

`R_DEBUG=1 r2 -d vmi://windows7-sp1:explorer`

**Comment by Necroxys77** [comment]
I think that this might be a good start.
`root:/home/necroxys# R_DEBUG=1 r2 -d vmi://windows7-sp1:explorer`
`Cannot open directory '/root/.local/share/radare2/plugins'`
`Cannot open directory '/usr/lib/radare2-extras/3.5.0-git'`
`Cannot open directory '/usr/lib/radare2-bindings/3.5.0-git'`
`[r] Cannot open 'vmi://windows7-sp1:explorer'`

Indeed, I don't have any of these directories:
`root:/usr/lib# ls | grep "radare"`
`radare2`
`root:/usr/lib# cd radare2/`
`root:/usr/lib/radare2# ls`
`3.5.0-git  last`
and:
`root:~/.local/share# ls`
`recently-used.xbel  webkitgtk`

**Comment by Wenzel** [comment]
I think the simple reason is that the plugin has been installed as simple user, and you need to run radare2 as root, therefore the plugin lookup directories are wrong.

can you try with `sudo -E r2 -d vmi://windows7-sp1:explorer` if this helps ?

**Comment by Necroxys77** [comment]
Now r2vmi runs properly, but I get a blue screen on the guest as soon as I type `dc` to track `NtOpenFile`. I'm trying to replicate your demo, doing the same steps that you did. I also read a [past issue](https://github.com/Wenzel/r2vmi/issues/36) but I can't figure out how to solve this issue.





![3](https://user-images.githubusercontent.com/17526371/56036406-16dcee80-5d2d-11e9-8ac7-a06ebd44197b.png)

Output of r2vmi:
```
[0x8268d99e]> db rekall.NtOpenFile 
__map_get
__map_get
__read, offset: 82849b10
__reg_read, type: 0, size:7168
[0x8268d99e]> dc
__breakpoint, set: 1, addr: 82849b10, hw: 0
__write
__continue, sig: 0
__wait
__wait: Listen to VMI events...
__wait: Listen to VMI events...
[...]
```

**Comment by Wenzel** [comment]
Are you running the guest with more than 1 vcpu ?

Please stick to 1 vcpu :relaxed:

**Comment by Necroxys77** [comment]
It worked, thank you!

One last thing: is there any guide to understand each option that you used in the demo?

EDIT: how did you "moved" through each assembly line in the `NtOpenFile` block?

**Comment by Wenzel** [comment]
> One last thing: is there any guide to understand each option that you used in the demo?

Look at the radare2 book.

> EDIT: how did you "moved" through each assembly line in the NtOpenFile block?

The `V` command for visual, then hit `p` to walk through the modes

**Comment by Wenzel** [comment]
Also, if you liked `r2vmi` you should also appreciate `pyvmidbg`
https://github.com/Wenzel/pyvmidbg

It's the project i'm working on at the moment, so more up to date, and compatible with any gdb frontend ! 🙂
